/* Signal Ledger page: evidence-first editorial dashboard, warm paper + ink + Kumquat Orange. */
import { useMemo, useState } from "react";
import type { ReactNode } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { ArrowDownRight, ArrowUpRight, Check, ChevronRight, CircleHelp, Database, ExternalLink, FileText, Github, Info, Play, ShieldCheck, Sparkles } from "lucide-react";
import { finsightData } from "@/data/finsightData";
import { downloadCsvReport, downloadPdfReport } from "@/lib/export";

const formatMonth = (value: string) => new Intl.DateTimeFormat("en-IN", { month: "short", year: "2-digit" }).format(new Date(value));
const formatBn = (value: number) => `${(value / 1000).toFixed(2)} B`;
const formatCr = (value: number) => `₹${(value / 100000).toFixed(1)} L Cr`;

function SectionKicker({ children }: { children: ReactNode }) { return <div className="kicker"><span className="kicker-mark" />{children}</div>; }
function SourceDocket({ children }: { children: ReactNode }) { return <div className="source-docket"><Database size={13} /> <span>{children}</span></div>; }
function Metric({ label, value, note, accent = "ink" }: { label: string; value: string; note: string; accent?: "orange" | "blue" | "green" | "ink" }) { return <div className={`metric metric-${accent}`}><p>{label}</p><strong>{value}</strong><span>{note}</span></div>; }

export default function Home() {
  const [view, setView] = useState<"volume" | "concentration">("volume");
  const [selectedMonth, setSelectedMonth] = useState<string>(finsightData.metrics.latest_month);
  const [showWalkthrough, setShowWalkthrough] = useState(false);
  const [exporting, setExporting] = useState<"pdf" | "csv" | null>(null);
  const [exportMessage, setExportMessage] = useState("");
  const currentRankings = useMemo(() => finsightData.rankings.filter((d) => d.month_start === selectedMonth), [selectedMonth]);
  const volumeDelta = finsightData.monthly.at(-1)!.volume_mn - finsightData.monthly[0].volume_mn;
  const volumeDeltaPct = (volumeDelta / finsightData.monthly[0].volume_mn) * 100;
  const handleExport = async (kind: "pdf" | "csv") => {
    setExporting(kind);
    setExportMessage("");
    try {
      if (kind === "csv") downloadCsvReport();
      else await downloadPdfReport();
      setExportMessage(`${kind.toUpperCase()} report ready in your downloads.`);
    } catch {
      setExportMessage("The report could not be generated. Try again after the dashboard finishes loading.");
    } finally {
      setExporting(null);
    }
  };

  return <div className="app-shell">
    <aside className="side-rail">
      <a className="brand" href="#top" aria-label="Finsight home"><span className="brand-mark"><span /><span /></span><span className="brand-word">finsight</span></a>
      <div className="rail-rule" />
      <nav className="rail-nav" aria-label="Primary navigation">
        <a className="active" href="#readout"><span className="nav-dot" />Readout</a>
        <a href="#evidence"><span className="nav-dot" />Evidence</a>
        <a href="#projection"><span className="nav-dot" />Projection</a>
        <a href="#method"><span className="nav-dot" />Method</a>
      </nav>
      <div className="rail-bottom"><div className="owner-chip"><span className="owner-avatar">SD</span><span><b>Maintained by</b><strong>Sundaram Dubey</strong></span></div><span className="v-label">v1.1.0 · 2026</span></div>
    </aside>

    <main id="top" className="main-canvas">
      <header className="topbar"><div className="breadcrumb"><span>FINSIGHT</span><ChevronRight size={14} /><span>UPI GROWTH STORY</span></div><div className="top-actions"><span className="status-pill"><span />19 verified months</span><div className="export-actions"><button onClick={() => handleExport("csv")} disabled={Boolean(exporting)}>{exporting === "csv" ? "Preparing…" : "CSV"}</button><button onClick={() => handleExport("pdf")} disabled={Boolean(exporting)}>{exporting === "pdf" ? "Preparing…" : "PDF"}</button></div><a href="https://github.com/sundaramvdubey/Finsight" target="_blank" rel="noreferrer" className="icon-link" aria-label="Open source repository"><Github size={17} /></a></div></header>

      {exportMessage && <div className="export-toast" role="status"><Check size={14}/>{exportMessage}</div>}

      <section id="readout" className="thesis-grid">
        <div className="thesis-copy"><SectionKicker>THE READOUT · NOV 2023 — OCT 2025</SectionKicker><h1>UPI is still growing.<br /><em>The distribution is the story.</em></h1><p className="dek">Transaction volume climbed from <b>{formatBn(finsightData.metrics.first_volume_mn)}</b> to <b>{formatBn(finsightData.metrics.latest_volume_mn)}</b> across the verified window. But the top two apps still account for <b>{finsightData.metrics.latest_top2_share_pct}%</b> of the latest month.</p><div className="thesis-foot"><span className="thesis-number">01</span><p>For a challenger like CRED, the opening is not “is UPI growing?” It is whether a smaller player can earn a high-intent wedge inside a market whose default behavior remains concentrated.</p></div></div>
        <div className="thesis-art"><img src="/manus-storage/finsight-editorial-paper_68627997.jpg" alt="Abstract paper and ledger texture" /><div className="art-caption">A measured read of the public record<br /><span>Volume-share first · value-share as cross-check</span></div><div className="art-stamp">PUBLIC<br />RECORD</div></div>
      </section>

      <section className="metric-strip" aria-label="Headline metrics"><Metric label="Verified observations" value="1,482" note="rows · 107 reported apps" accent="blue" /><Metric label="Volume change" value={`+${volumeDeltaPct.toFixed(1)}%`} note="Nov ’23 → Oct ’25" accent="orange" /><Metric label="Top-two share" value={`${finsightData.metrics.latest_top2_share_pct}%`} note="PhonePe + Google Pay · Oct ’25" accent="green" /><Metric label="Model test error" value={`${finsightData.metrics.test_mape_pct}%`} note="MAPE · last 4 real months held out" accent="ink" /></section>

      <section id="evidence" className="evidence-section section-block"><div className="section-heading"><div><SectionKicker>01 · EVIDENCE</SectionKicker><h2>Growth is real. Concentration is, too.</h2></div><div className="view-switch" role="tablist" aria-label="Chart view"><button className={view === "volume" ? "selected" : ""} onClick={() => setView("volume")} role="tab">Volume</button><button className={view === "concentration" ? "selected" : ""} onClick={() => setView("concentration")} role="tab">Top-two share</button></div></div>
        <div className="chart-card"><div className="chart-note"><span className="chart-legend"><i className={view === "volume" ? "blue-dot" : "orange-dot"} />{view === "volume" ? "Monthly UPI transaction volume" : "PhonePe + Google Pay share"}</span><span className="chart-unit">{view === "volume" ? "BILLION TRANSACTIONS" : "PERCENT OF VOLUME"}</span></div><div className="chart-wrap"><ResponsiveContainer width="100%" height={330}><AreaChart data={[...finsightData.monthly]} margin={{ top: 20, right: 18, left: -12, bottom: 0 }}><defs><linearGradient id="volumeFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#4B7C91" stopOpacity={0.25}/><stop offset="100%" stopColor="#4B7C91" stopOpacity={0}/></linearGradient><linearGradient id="shareFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#E66D3F" stopOpacity={0.22}/><stop offset="100%" stopColor="#E66D3F" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#DDD6C8" strokeDasharray="2 5"/><XAxis dataKey="month_start" tickFormatter={formatMonth} tick={{ fill: "#7C837B", fontSize: 11, fontFamily: "IBM Plex Mono" }} tickLine={false} axisLine={false} interval={2}/><YAxis tick={{ fill: "#7C837B", fontSize: 11, fontFamily: "IBM Plex Mono" }} tickLine={false} axisLine={false} tickFormatter={(v) => view === "volume" ? `${(v/1000).toFixed(0)}B` : `${v}%`} domain={view === "volume" ? [10000, 21000] : [80, 90]}/><Tooltip contentStyle={{ background: "#1D2B2A", border: "0", borderRadius: 2, color: "#F8F4EB", fontFamily: "IBM Plex Mono", fontSize: 12 }} labelFormatter={(l) => formatMonth(String(l))} formatter={(v: number) => [view === "volume" ? `${formatBn(v)} transactions` : `${v.toFixed(2)}%`, view === "volume" ? "Volume" : "Top two"]}/>{view === "volume" ? <Area type="monotone" dataKey="volume_mn" stroke="#4B7C91" strokeWidth={3} fill="url(#volumeFill)" /> : <Area type="monotone" dataKey="top2_share_pct" stroke="#E66D3F" strokeWidth={3} fill="url(#shareFill)" />}</AreaChart></ResponsiveContainer></div><SourceDocket>NPCI UPI Ecosystem Statistics · app-wise monthly exports · {finsightData.metrics.months_used} verified months</SourceDocket></div>
        <div className="annotation-row"><div className="annotation orange-line"><strong>What the line says</strong><p>Volume rose {volumeDeltaPct.toFixed(1)}% in the verified record, despite several month-to-month pullbacks.</p></div><div className="annotation"><strong>What it does not say</strong><p>A rising market does not imply a broadening one. The latest top-two share remains above 83%.</p></div></div>
      </section>

      <section className="split-section section-block"><div className="rank-panel"><div className="section-heading compact"><div><SectionKicker>02 · APP LENS</SectionKicker><h2>Who owns the latest month?</h2></div><select value={selectedMonth} onChange={(e) => setSelectedMonth(e.target.value)} aria-label="Choose a month">{finsightData.monthly.map((m) => <option key={m.month_start} value={m.month_start}>{formatMonth(m.month_start)}</option>)}</select></div><div className="mini-bars">{currentRankings.map((app) => <div className="rank-row" key={app.app_name}><div className="rank-meta"><span className="rank-num">0{app.rank}</span><span className="rank-name">{app.app_name}</span><b>{app.share_pct.toFixed(1)}%</b></div><div className="bar-track"><span style={{ width: `${Math.max(4, app.share_pct)}%` }} /></div></div>)}</div><SourceDocket>Share of monthly transaction volume · selected month</SourceDocket></div><div className="meaning-panel"><img src="/manus-storage/finsight-data-structure_b731fb98.jpg" alt="Abstract data structure illustration" /><div className="meaning-overlay"><SectionKicker>THE SO-WHAT</SectionKicker><h2>Scale is table stakes. Distribution is the moat.</h2><p>For CRED, the strategic question is not whether to chase the market’s total growth. It is whether a distinct use case can break through default app behavior.</p><a href="#method" className="text-link">Read the method <ArrowUpRight size={15}/></a></div></div></section>

      <section id="projection" className="projection-section section-block"><div className="projection-copy"><SectionKicker>03 · PROJECTION</SectionKicker><h2>A straight line into<br /><em>an uncertain quarter.</em></h2><p>One linear regression, fit on all 19 verified observations, projects continued growth through Jan 2026. The band is intentionally visible: it is not a promise.</p><div className="model-badge"><Sparkles size={15}/><span>LINEAR REGRESSION · CALENDAR-MONTH INDEX</span></div></div><div className="projection-chart"><ResponsiveContainer width="100%" height={260}><LineChart data={[...finsightData.projection]} margin={{ top: 18, right: 20, left: -18, bottom: 0 }}><CartesianGrid vertical={false} stroke="#DDD6C8" strokeDasharray="2 5"/><XAxis dataKey="month" tickFormatter={formatMonth} tick={{ fill: "#7C837B", fontSize: 11, fontFamily: "IBM Plex Mono" }} tickLine={false} axisLine={false}/><YAxis tick={{ fill: "#7C837B", fontSize: 11, fontFamily: "IBM Plex Mono" }} tickLine={false} axisLine={false} tickFormatter={(v) => `${(v/1000).toFixed(0)}B`}/><Tooltip contentStyle={{ background: "#1D2B2A", border: "0", borderRadius: 2, color: "#F8F4EB", fontFamily: "IBM Plex Mono", fontSize: 12 }} labelFormatter={(l) => formatMonth(String(l))} formatter={(v: number) => [`${formatBn(v)} transactions`, "Projected"]}/><Line type="monotone" dataKey="projected_volume_mn" stroke="#E66D3F" strokeWidth={3} dot={{ r: 5, fill: "#E66D3F", stroke: "#F8F4EB", strokeWidth: 2 }}/><Line type="monotone" dataKey="lower_95" stroke="#C9A391" strokeDasharray="4 5" strokeWidth={1.5} dot={false}/><Line type="monotone" dataKey="upper_95" stroke="#C9A391" strokeDasharray="4 5" strokeWidth={1.5} dot={false}/></LineChart></ResponsiveContainer><div className="projection-legend"><span><i className="orange-dot" />projection</span><span><i className="band-line" />approx. 95% residual band</span></div></div><div className="projection-table"><div className="table-head"><span>Month</span><span>Projection</span><span>Range</span></div>{finsightData.projection.map((row) => <div className="table-row" key={row.month}><span>{formatMonth(row.month)}</span><b>{formatBn(row.projected_volume_mn)}</b><span>{formatBn(row.lower_95)} — {formatBn(row.upper_95)}</span></div>)}</div></section>

      <section id="method" className="method-section section-block"><div className="method-intro"><SectionKicker>04 · METHOD & LIMITS</SectionKicker><h2>Good analysis shows its seams.</h2><p>This is a transparent capstone product, not a forecasting oracle. The strongest thing in the room is the evidence trail.</p><a className="download-link" href="https://github.com/sundaramvdubey/Finsight/blob/main/memo/memo.md" target="_blank" rel="noreferrer"><FileText size={16}/> Open the one-page memo <ExternalLink size={13}/></a></div><div className="method-grid"><div className="method-card"><span className="method-index">01</span><h3>Why 19 of 24?</h3><p>Five months were byte-identical to their preceding month in the app-wise export. They were excluded rather than interpolated. No verified app-wise figures could be sourced for those gaps in the original analysis.</p><span className="method-status warn"><Info size={13}/> named limitation</span></div><div className="method-card"><span className="method-index">02</span><h3>Error, reported honestly</h3><p>The temporal holdout test MAPE is <b>1.69%</b> versus <b>2.15%</b> on train. With only 19 real observations and no seasonality term, this is directional—not proof of generalization.</p><span className="method-status check"><Check size={13}/> no overfitting signal in split</span></div><div className="method-card"><span className="method-index">03</span><h3>Provenance by default</h3><p>Primary source: NPCI’s public UPI Ecosystem Statistics. Cross-checks use NPCI press releases only for sanity checks. Cleaned rows retain source_file lineage in the processed dataset.</p><span className="method-status check"><ShieldCheck size={13}/> source trail documented</span></div></div></section>

      <section className="download-center section-block"><div><SectionKicker>EXPORT · LOCAL FIRST</SectionKicker><h2>Take the read with you.</h2><p>Everything here is generated in your browser. CSV includes the verified monthly aggregates, projections, and ranking rows. PDF captures the dashboard with charts, caveats, and provenance.</p></div><div className="download-buttons"><button className="outline-button" onClick={() => handleExport("csv")} disabled={Boolean(exporting)}><Database size={15}/>{exporting === "csv" ? "Preparing CSV…" : "Download CSV report"}</button><button className="outline-button" onClick={() => handleExport("pdf")} disabled={Boolean(exporting)}><FileText size={15}/>{exporting === "pdf" ? "Preparing PDF…" : "Download PDF report"}</button></div></section>

      <section className="walkthrough"><div className="walkthrough-image"><img src="/manus-storage/finsight-walkthrough-cover_0adf14bc.jpg" alt="Editorial walkthrough cover" /><div className="play-button"><Play fill="currentColor" size={20}/></div></div><div className="walkthrough-copy"><SectionKicker>03:00 · WALKTHROUGH</SectionKicker><h2>See the answer before you see the interface.</h2><p>A three-minute guided tour: the thesis, the evidence, the projection, and the caveat that keeps the whole thing honest.</p><div className="walkthrough-meta"><span><span className="live-dot" />Video walkthrough</span><span>Owner · Sundaram Dubey</span></div><button className="outline-button" onClick={() => setShowWalkthrough(true)}><Play size={15}/> Open walkthrough</button></div></section>

      {showWalkthrough && <div className="walkthrough-modal" role="dialog" aria-modal="true" aria-labelledby="walkthrough-title"><div className="walkthrough-dialog"><button className="modal-close" onClick={() => setShowWalkthrough(false)} aria-label="Close walkthrough">×</button><SectionKicker>03:00 · GUIDED READ</SectionKicker><h2 id="walkthrough-title">The Finsight answer, in four stops.</h2><div className="guided-steps"><div><span>01</span><p><b>Thesis.</b> UPI volume rises, but the top two apps still own the default behavior.</p></div><div><span>02</span><p><b>Evidence.</b> Toggle the chart and use the month selector to inspect concentration directly.</p></div><div><span>03</span><p><b>Projection.</b> A simple linear regression points upward, with an intentionally visible residual band.</p></div><div><span>04</span><p><b>Caveat.</b> Five duplicated months were excluded; the test error is directional, not a guarantee.</p></div></div><a className="download-link" href="https://github.com/sundaramvdubey/Finsight/blob/main/docs/WALKTHROUGH.md" target="_blank" rel="noreferrer">Open the narration script <ExternalLink size={13}/></a></div></div>}

      <footer className="footer"><div><a className="brand footer-brand" href="#top"><span className="brand-mark"><span /><span /></span><span className="brand-word">finsight</span></a><p>UPI growth, read with receipts.</p></div><div className="footer-links"><a href="https://github.com/sundaramvdubey/Finsight" target="_blank" rel="noreferrer">Source repository <ExternalLink size={13}/></a><a href="https://www.npci.org.in/what-we-do/upi/upi-ecosystem-statistics" target="_blank" rel="noreferrer">NPCI source <ExternalLink size={13}/></a><span>v1.1.0 · MIT code license</span></div></footer>
    </main>
  </div>;
}
